kind: BuildConfig
apiVersion: v1
metadata:
  name: python-hostname-service-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any

          stages {
            stage('Build image') {
              when {
                expression {
                  openshift.withCluster() {
                    return !openshift.selector('bc', 'python-hostname-service').exists();
                  }
                }
              }
              steps {
                script {
                  openshift.withCluster() {
                    openshift.newApp('rhscl/python-36-rhel7:latest~https://github.com/ricardo-forte-redhat/python-hostname-service.git')
                  }
                }
              }
            }
            stage('Deploy') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      def rm = openshift.selector('dc','python-hostname-service').rollout()
                      timeout(5) {
                        openshift.selector('dc','python-hostname-service').related('pods').untilEach(1) {
                          return (it.object().status.phase == 'Running')
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }